# Calls using the REST Client VScode extension

# Intro

### https://apidoc.tatum.io/tag/Data-API
curl -i -X GET \
  'https://api.tatum.io/v3/data/blocks/latest?chain=celo-testnet' \



# RPC

###  https://apidoc.tatum.io/tag/Node-RPC
curl -i -X POST \
  https://api.tatum.io/v3/blockchain/node/celo-testnet/ \
  -H 'Content-Type: application/json' \
  # -H "x-api-key": "{{$TATUMIO_API_KEY}}"
  -d '{
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": [],
    "id": 2
  }'

